name: Check Flutter Dependencies

on:
  schedule:
    - cron: "0 1 * * *" # Runs every day at 8:00 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Check for outdated Flutter packages
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PROJECT_NAME: Flutter Usecase Template
        run: |
          output=$(flutter pub outdated)
          echo "$output"
          echo "$output" > outdated_report.txt          
          upgradable_packages=$(awk '/direct dependencies:/,0' outdated_report.txt | tail -n +2)

          if [ -n "$upgradable_packages" ]; then
            message="⚠️ *$PROJECT_NAME packages have updates available!*\n\`\`\`\n$upgradable_packages\n\`\`\`"
          else
            message="✅ $PROJECT_NAME dependencies are up to date!"
          fi

          # Escape JSON properly
          payload=$(jq -n --arg content "$message" '{content: $content}')

          curl -H "Content-Type: application/json" \
                -X POST \
                -d "$payload" \
                $DISCORD_WEBHOOK
